version: '3.9'

volumes:
  pgdata: {}

services:
  db:
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: techfood
      POSTGRES_USER: techfood
      POSTGRES_PASSWORD: techfood123

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/techfood
      SPRING_DATASOURCE_USERNAME: techfood
      SPRING_DATASOURCE_PASSWORD: techfood123
    ports:
      - "8080:8080"
    restart: always