   CREATE TABLE IF NOT EXISTS USUARIOS(
   USERNAME VARCHAR(30) PRIMARY KEY,
   PASSWORD VARCHAR(60),
   DATA_CRIACAO_CONTA DATE,
   DATA_ALTERACAO_CONTA DATE,
   DATA_ALTERACAO_SENHA DATE
   );

CREATE TABLE IF NOT EXISTS CLIENTES(
    ID BIGSERIAL PRIMARY KEY,
    CPF VARCHAR(14),
    NOME VARCHAR(50),
    EMAIL VARCHAR(50),
    TELEFONE VARCHAR(15),
    USERNAME VARCHAR(30) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME)
    );

CREATE TABLE IF NOT EXISTS PROPRIETARIOS(
    ID BIGSERIAL PRIMARY KEY,
    CPF VARCHAR(14),
    NOME VARCHAR(50),
    EMAIL VARCHAR(50),
    TELEFONE VARCHAR(15),
    USERNAME VARCHAR(30) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME)
    );

CREATE TABLE IF NOT EXISTS ENDERECOS(
    ID BIGSERIAL PRIMARY KEY,
    ID_CLIENTE BIGINT,
--    ID_RESTAURANTE BIGINT,
    RUA VARCHAR(50),
    CEP VARCHAR(15),
    NUMERO VARCHAR(10),
    BAIRRO VARCHAR(20),
    CIDADE VARCHAR(15),
    COMPLEMENTO VARCHAR(30),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
--    FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTES(ID)
    );

CREATE TABLE IF NOT EXISTS RESTAURANTES(
    ID BIGSERIAL PRIMARY KEY,
    ID_PROPRIETARIO BIGINT NOT NULL,
    NOME VARCHAR(20),
    TELEFONE VARCHAR(11),
    FOREIGN KEY (ID_PROPRIETARIO) REFERENCES PROPRIETARIOS(ID)
    );