CREATE TABLE CLIENTES(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CPF VARCHAR(14),
    NOME VARCHAR(30),
    EMAIL VARCHAR(50),
    LOGIN VARCHAR(20) UNIQUE,
    TELEFONE VARCHAR(15),
    PASSWORD VARCHAR(80)
    );

CREATE TABLE PROPRIETARIOS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CPF VARCHAR(14),
    NOME VARCHAR(30),
    EMAIL VARCHAR(50),
    LOGIN VARCHAR(20) UNIQUE,
    TELEFONE VARCHAR(15),
    PASSWORD VARCHAR(60)
    );

CREATE TABLE ENDERECOS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE BIGINT NOT NULL,
    RUA VARCHAR(50),
    CEP VARCHAR(15),
    NUMERO VARCHAR(10),
    BAIRRO VARCHAR(20),
    CIDADE VARCHAR(15),
    COMPLEMENTO VARCHAR(30),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
    );

CREATE TABLE CONTAS_BANCARIAS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_CONTA VARCHAR(20),
    BANCO VARCHAR(20)
    );

CREATE TABLE RESTAURANTES(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_PROPRIETARIO BIGINT NOT NULL,
    ID_CONTA_BANCARIA BIGINT NOT NULL,
    NOME VARCHAR(20),
    TELEFONE VARCHAR(11),
    FOREIGN KEY (ID_PROPRIETARIO) REFERENCES PROPRIETARIOS(ID),
    FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES CONTAS_BANCARIAS(ID)
    );

    INSERT INTO PROPRIETARIOS (CPF, NOME, EMAIL, LOGIN, TELEFONE, PASSWORD)
        VALUES ('213.000.201-55', 'ROBERTO SILVA', 'ROBERTO.SILVA@GMAIL.COM', 'ROBERTO.SILVA', '4199999-3333', 'X123X4');

    INSERT INTO CLIENTES (CPF, NOME, EMAIL, LOGIN, TELEFONE, PASSWORD)
        VALUES ('313.001.201-55', 'MICHELE ANTUNES', 'MICHELE.ANTUNES@GMAIL.COM', 'MICHELE.ANTUNES', '6599999-0001', 'senha1234');

    INSERT INTO ENDERECOS (ID_CLIENTE, RUA, CEP, NUMERO, BAIRRO, CIDADE, COMPLEMENTO)
        VALUES (1, 'RUA GASTRONOMICA', '80090-000', '123', 'LEBLON', 'RIO DE JANEIRO', 'CASA 3');

    INSERT INTO CONTAS_BANCARIAS (NUMERO_CONTA, BANCO)
        VALUES('12345-0','BANCO DO BRASIL');

    INSERT INTO RESTAURANTES (ID_PROPRIETARIO, ID_CONTA_BANCARIA, NOME, TELEFONE)
        VALUES (1,1, 'COMIDA BRASILEIRA', '653333-3333');