   CREATE TABLE USUARIOS(
   USERNAME VARCHAR(20) PRIMARY KEY,
   PASSWORD VARCHAR(60),
   DATA_CRIACAO_CONTA DATE,
   DATA_ALTERACAO_CONTA DATE,
   DATA_ALTERACAO_SENHA DATE
   );

CREATE TABLE CLIENTES(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CPF VARCHAR(14),
    NOME VARCHAR(30),
    EMAIL VARCHAR(50),
    TELEFONE VARCHAR(15),
    USERNAME VARCHAR(20) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME)
    );

CREATE TABLE PROPRIETARIOS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CPF VARCHAR(14),
    NOME VARCHAR(30),
    EMAIL VARCHAR(50),
    TELEFONE VARCHAR(15),
    USERNAME VARCHAR(20) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME)
    );

CREATE TABLE ENDERECOS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE BIGINT NOT NULL,
    RUA VARCHAR(50),
    CEP VARCHAR(15),
    NUMERO VARCHAR(10),
    BAIRRO VARCHAR(20),
    CIDADE VARCHAR(15),
    COMPLEMENTO VARCHAR(30),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
    );

CREATE TABLE RESTAURANTES(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_PROPRIETARIO BIGINT NOT NULL,
    NOME VARCHAR(20),
    TELEFONE VARCHAR(11),
    FOREIGN KEY (ID_PROPRIETARIO) REFERENCES PROPRIETARIOS(ID)
    );

    INSERT INTO USUARIOS (USERNAME, PASSWORD)
        VALUES ('ROBERTO.SILVA', '1234R'),
               ('MICHELE.ANTUNES','1234M');

    INSERT INTO PROPRIETARIOS (CPF, NOME, EMAIL, TELEFONE, USERNAME)
        VALUES ('213.000.201-55', 'ROBERTO SILVA', 'ROBERTO.SILVA@GMAIL.COM', '4199999-3333', 'ROBERTO.SILVA');

    INSERT INTO CLIENTES (CPF, NOME, EMAIL, TELEFONE, USERNAME)
        VALUES ('313.001.201-55', 'MICHELE ANTUNES', 'MICHELE.ANTUNES@GMAIL.COM', '6599999-0001', 'MICHELE.ANTUNES');

    INSERT INTO ENDERECOS (ID_CLIENTE, RUA, CEP, NUMERO, BAIRRO, CIDADE, COMPLEMENTO)
        VALUES (1, 'RUA GASTRONOMICA', '80090-000', '123', 'LEBLON', 'RIO DE JANEIRO', 'CASA 3');

    INSERT INTO RESTAURANTES (ID_PROPRIETARIO, NOME, TELEFONE)
        VALUES (1, 'COMIDA BRASILEIRA', '653333-3333');