CREATE TABLE IF NOT EXISTS USUARIOS(
   USERNAME VARCHAR(30) PRIMARY KEY,
   PASSWORD VARCHAR(60),
   DATA_CRIACAO_CONTA DATE,
   DATA_ALTERACAO_CONTA DATE,
   DATA_ALTERACAO_SENHA DATE
);

CREATE TABLE IF NOT EXISTS CLIENTES(
    ID BIGSERIAL PRIMARY KEY,
    CPF VARCHAR(14),
    NOME VARCHAR(50),
    EMAIL VARCHAR(50),
    TELEFONE VARCHAR(15),
    USERNAME VARCHAR(30) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PROPRIETARIOS(
    ID BIGSERIAL PRIMARY KEY,
    CPF VARCHAR(14),
    NOME VARCHAR(50),
    EMAIL VARCHAR(50),
    TELEFONE VARCHAR(15),
    USERNAME VARCHAR(30) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESTAURANTES(
    ID BIGSERIAL PRIMARY KEY,
    ID_PROPRIETARIO BIGINT NOT NULL,
    NOME VARCHAR(20),
    TELEFONE VARCHAR(11),
    FOREIGN KEY (ID_PROPRIETARIO) REFERENCES PROPRIETARIOS(ID) ON DELETE CASCADE
);

CREATE TYPE tipo_endereco AS ENUM ('CLIENTE', 'RESTAURANTE');

CREATE TABLE IF NOT EXISTS ENDERECOS(
    ID BIGSERIAL PRIMARY KEY,
    ID_CLIENTE BIGINT,
    ID_RESTAURANTE BIGINT,
    TIPO tipo_endereco NOT NULL,
    RUA VARCHAR(50) NOT NULL,
    CEP VARCHAR(15) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    BAIRRO VARCHAR(20) NOT NULL,
    CIDADE VARCHAR(15) NOT NULL,
    COMPLEMENTO VARCHAR(30),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTES(ID) ON DELETE CASCADE
);
